Global refactoring
LuckyGeck/TorrentChecker pull request #1
Opened 2017-01-02 21:09 UTC by bamx23

This bunch of changes makes the code more "pythonic".

2017-02-06 22:08 UTC, LuckyGeck requested changes
Куча комментов по коду. Глубоко посмотреть только несколько файлов. Как починятся эти комменты - посмотрю еще.

2017-02-06 22:08 UTC, LuckyGeck commented on README.md
> +    - На данный момент поддериваются варианты:
поддерживаются

2017-02-06 22:08 UTC, LuckyGeck commented on README.md
> +* `descr`
Теперь вроде description

2017-02-06 22:08 UTC, LuckyGeck commented on README.md
> +        + В файле строка будет выглядеть так: `"descr" : "ТБВ 6 сезон"`
И тут тоже

2017-02-06 22:08 UTC, LuckyGeck commented on README.md
> +2. Пропишите [API ключ](https://core.telegram.org/bots#6-botfather) вашего бота и [ваш username](https://telegram.org/faq#q-what-are-usernames-how-do-i-get-one) в `settings.py`.
Вроде уже не используется этот файл для настроек. Надо везде поменять на json.

2017-02-06 22:08 UTC, LuckyGeck commented on settings.py
> +    dir = os.path.dirname(os.path.realpath(__file__))
Переопределение builtin функции. Не очень хорошо.

2017-02-06 22:08 UTC, LuckyGeck commented on settings.py
> +import json
Я бы либо все импорты внутрь load_settings занес, либо наоборт

2017-02-06 22:08 UTC, LuckyGeck commented on settings.py
> +        return json.load(settings_file)
return json.load(open(settings_file_path))

2017-02-06 22:08 UTC, LuckyGeck commented on settings.py
> +    with open(settings_file_path) as settings_file:
Проверить, что с кодировками все ок. Лучше всего файлы в utf8 все держать для консистентности.

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +from plugins import plugins
https://www.python.org/dev/peps/pep-0008/#imports

> Imports should be grouped in the following order:
> 
> * standard library imports
> * related third party imports
> * local application/library specific imports

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +    encoding = shows_settings["list"].get("enc", "cp1251")
Я бы cp1251 на utf8 заменил. 21 век на дворе.

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +    try:
Лучше падать или по крайней мере сказать об ошибке чтения.

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +            torrents_list = json.load(torrents_file, encoding=encoding)
return json.load(open(..),..)

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +    json_string = json.dumps(torrents_list,
json.dump() умеет прямо в файл дампить.

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +        print "No such server handler: {}".format(torrent["tracker"])
Лучше сразу выйти и остальной код вынести из else ветки.

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +        plugin = plugins.servers[torrent["tracker"]]
if заменить на plugin = plugins.servers.get(torrent["tracker"], None) и потом проверку plugins is None

2017-02-06 22:08 UTC, LuckyGeck commented on shows_updater.py
> +        data = plugin.load_torrent(torrent_id)
В трай бы обернуть и лог добавить

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/__init__.py
> +        self.on_finish_plugins = []
Я бы выделил эту инициализацию в метод _reset - там ниже в load() она же производится.

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/__init__.py
> +            # server plugin
Комменты в этой функции можно убрать - ясности не вносят.

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +    active = False
14 и 15 строки надо убрать - эти переменные будут принадлежать классу, а не объекту.

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +        self.active = settings.get('active', False)
Может active тру по дефолту сделать? И поубирать этот debug и active из сэмплов где он равен дефолту

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +    login = ''
Опять же - эти штуки статические получаются. Надо выпилить. Аналогочно и в других классах надо так сделать.

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +        plugin_name = self.__class__.get_plugin_name()
Тут точно __class__ надо? Без него не прокатит?

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +    def get_server_name(self):
Можно воспользоваться @abc.abstractmethod и вообще всем модулем abc (https://docs.python.org/2/library/abc.html)

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +        if not self.cookies:
Инвертировать условие лучше - if self.cookies: return

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +        if not self.opener:
Аналогично - инвертировать условие

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +        if not self.is_authorized(self.opener):
Инвертировать условие

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/base.py
> +            self.log_debug('Auth...')
nit: я бы это лучше перевел на использование logging. но можно и забить пока

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/nnm-club.py
> +        return 'nnm-club', 'nnmclub'
А точно надо давать возможность несколько имен плагину экспозить?

2017-02-06 22:08 UTC, LuckyGeck commented on plugins/twitter_notif.py
> +        base.OnNewTorrentPlugin.__init__(self, settings)
Я бы воткнул проверку на наличие ttytter прямо во время загрузки плагина. Чтобы он тогда ругнулся.

2017-02-07 17:57 UTC, bamx23 commented on plugins/__init__.py
> +        self.on_finish_plugins = []
Тогда IDE ругается, что проперти не в ините созданы

2017-02-07 18:32 UTC, bamx23 reviewed
Внес правки по замечаниям, жду вторую волну (:

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +        self.active = settings.get('active', False)
Не, делать по дефолту тру не стоит, т.к. в семпле многие плагины требуют настройки. Так настроил - включил. А если в семпле не показать, то и не ясно будет, какие флаги есть

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +            self.log_debug('Auth...')
Давай пока подзабьем, но учту

2017-02-07 18:32 UTC, bamx23 commented on plugins/nnm-club.py
> +        return 'nnm-club', 'nnmclub'
Эта логика была заложена ещё тобой) Идея мне понравилась, почему бы и нет

2017-02-07 18:32 UTC, bamx23 commented on plugins/twitter_notif.py
> +        base.OnNewTorrentPlugin.__init__(self, settings)
Не очень, ведь тогда если даже ты отключил плагин, он всё равно будет ругаться при создании.

2017-02-07 18:32 UTC, bamx23 commented on settings.py
> +import json
Плюсую, занес

2017-02-07 18:32 UTC, bamx23 commented on README.md
> +    - На данный момент поддериваются варианты:
Исправил

2017-02-07 18:32 UTC, bamx23 commented on README.md
> +* `descr`
Ага, поправил

2017-02-07 18:32 UTC, bamx23 commented on README.md
> +        + В файле строка будет выглядеть так: `"descr" : "ТБВ 6 сезон"`
Ага

2017-02-07 18:32 UTC, bamx23 commented on README.md
> +2. Пропишите [API ключ](https://core.telegram.org/bots#6-botfather) вашего бота и [ваш username](https://telegram.org/faq#q-what-are-usernames-how-do-i-get-one) в `settings.py`.
Да, уже JSON

2017-02-07 18:32 UTC, bamx23 commented on plugins/__init__.py
> +            # server plugin
Убрал

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +    active = False
Буду знать, убрал

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +    login = ''
Выпилил

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +        plugin_name = self.__class__.get_plugin_name()
Прокатит, убрал. Это привык к ObjC

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +    def get_server_name(self):
Что-то не особо вкурил профита от этого. Пояснишь?

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +        if not self.cookies:
Приучили тут к тому, чтобы у метода был один `return`. Поправил

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +        if not self.opener:
Готово

2017-02-07 18:32 UTC, bamx23 commented on plugins/base.py
> +        if not self.is_authorized(self.opener):
+

2017-02-07 18:32 UTC, bamx23 commented on settings.py
> +    dir = os.path.dirname(os.path.realpath(__file__))
Сорян, поправил

2017-02-07 18:32 UTC, bamx23 commented on settings.py
> +    with open(settings_file_path) as settings_file:
Всё в UTF-8 с LF

2017-02-07 18:32 UTC, bamx23 commented on settings.py
> +        return json.load(settings_file)
Точно, поправил

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +from plugins import plugins
О! Думал что должно быть что-то такое. А в obj-c я приучил себя к другому порядку))

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +    try:
Согласен, пусть падает

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +            torrents_list = json.load(torrents_file, encoding=encoding)
Готово

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +    json_string = json.dumps(torrents_list,
Ага, переделал

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +        print "No such server handler: {}".format(torrent["tracker"])
Да, привычки. Поправил

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +        plugin = plugins.servers[torrent["tracker"]]
Ага, забыл это сделать

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +        data = plugin.load_torrent(torrent_id)
трай в мейне

2017-02-07 18:32 UTC, bamx23 commented on shows_updater.py
> +    encoding = shows_settings["list"].get("enc", "cp1251")
Да, давно пора

2017-02-11 09:50 UTC, LuckyGeck commented on plugins/base.py
> +        self.active = settings.get('active', False)
Я тут посмотрел - флаг debug по сути используется только при выводе логов. Давай его просто выпилим и сделаем command line flag  -v -vv и все такое. А логи будем писать через logging - там есть поддержка уровней логирования.

2017-02-11 09:54 UTC, LuckyGeck commented on plugins/base.py
> +    def get_server_name(self):
Это чтобы делать иерархии классов с абстрактной базой. Т.е. по сути аналог абстрактного класса в С++, в котором ты задаешь методы, которые обязательно надо override-ить в наследниках. Наш интерфейс плагина можно сделать абстрактным классом и тогда все плагины обязательно должны реализовывать этот метод

2017-02-11 09:59 UTC, LuckyGeck commented on plugins/base.py
> +        if not self.cookies:
Поясню, зачем делать ранний выход. Это приводит к меньшению максимального уровня вложенности в коде. Такой код обычно читается легче и менее вероятно посадить там логическую ошибку.

2017-02-11 10:02 UTC, LuckyGeck commented on plugins/nnm-club.py
> +        return 'nnm-club', 'nnmclub'
Я ж не говорю, что я писал хороший код. Но если сейчас делать рефакторинг, то можно посносить легаси. Если тебе понравилась идея, то ок.

2017-02-11 11:07 UTC, LuckyGeck requested changes

2017-02-11 11:07 UTC, LuckyGeck commented on README.md
> +5. Впишите полученный `chat_id` в соответствующее поле в `settings.py`.
json :) и поищи еще по файлу, плз. может найдешь.

2017-02-11 11:07 UTC, LuckyGeck commented on plugins/base.py
> +        raise NotImplementedError
тут pass достаточно делать. и ниже аналогично. и к каждому @abstractmethod-у я бы добавил однострочный коммент - типа когда он вызывается

2017-02-11 11:07 UTC, LuckyGeck commented on plugins/base.py
> +
Для этих базовый классов неплохо бы хотябы однострочный коммент проставить.

2017-02-11 17:56 UTC, bamx23 reviewed
Перелопатил ещё кусок, добавил кучу аннотаций типов и документации к методам. Теперь бы ещё мою грамматику прочекать)

2017-02-11 17:56 UTC, bamx23 commented on README.md
> +5. Впишите полученный `chat_id` в соответствующее поле в `settings.py`.
Исправил, последняя)

2017-02-11 17:56 UTC, bamx23 commented on plugins/base.py
> +
Да, согласен, добавил

2017-02-11 17:56 UTC, bamx23 commented on plugins/base.py
> +        raise NotImplementedError
Добавил коментов

2017-02-11 17:56 UTC, bamx23 commented on plugins/nnm-club.py
> +        return 'nnm-club', 'nnmclub'
Психанул и вообще серьезно переделал эту логику (:

2017-02-14 10:54 UTC, LuckyGeck requested changes
* Комменты к методам обычно пишут, чтобы они отвечали на вопрос "что делает метод". Типа "returnS ...", "processES..."
* Однострочные комменты (docstring) лучше оставлять однострочными, а не делать на несколько строк
* Давай это ревью закончим и будем делать несколько маленьких потом - мне реально очень сложно такие полотна читать

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/__init__.py
> +        Return server plugin with specific name
Returns a corresponding server plugin for a given 'server_name'.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/__init__.py
> +        Return server plugin that can process specific torrent
Return**s** a server plugin that can process a given torrent

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/__init__.py
> +        Process all on-start plugins. Should be called in the beginning
Process**es**
at the beginning

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +class Torrent(object):
Может отнаследоваться от dict-а? А то ты там перегружешь всякое - можешь и лишнего из __dict__ забрать чуть что. Например, ты функции тоже сериализуешь)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/__init__.py
> +        Process all plugins that handle new torrent loads.
Triggers 'on_new_torrent_process' (название кстати странное) for all registered plugins.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/__init__.py
> +        Process all on-finish plugins. Should be called in the end of
По аналогии с комментами выше.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        import hashlib
Тут лучше вынести вверх импорт.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Check if torrent could be processed with this plugin
Check**s** if the torrent can be processed by a current plugin.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        :return: True if torrent could be processed with this plugin
Аналогично комменту выше

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Check authorization status(usually by trying to load resource not
...status_(usually...

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Perform authorization at torrent tracker
Authorize on a torrent tracker.
Странно, что мы тут не кидаем исключений или хотя бы код ошибки не возвращаем

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Return absolute URL of torrent(topic)
of -> for a torrent (topic)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Load torrent description(title of a topic)
Loads a description for a given torrent (a title of a corresponding topic)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Load torrent file
Loads a contents of a given torrent file from a remote server

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        :return: Data of torrent file in string representation and
Этот коммент не коррелирует с возвращаемым значением) По комменту - ты возвращаешь пару.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Return torrents matching query and with specific type.
Returns torrents, that match a given query and are within a given category. (Если я вообще правильно понял, что происходит)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        :param query: Query string for search
Search string

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +    something that is should be done before torrents checking process.
Base class for plugins that implement on-start logic. When registered, these plugins will be triggered at the very beginning of the main process.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Called in the beginning of main process.
Does some preparations before the torrents' checking process.

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +    Base class for plugins that handle a fact of new torrents downloading.
Тут точно имеется в виду то, что написано? Коммент ясности не внес - он немного отличается от того, что в докстринге к on_new_torrent_process написано.
Давай может для тех классов, которые с одним методом, докстринги уберем (если они дублируют по сути докстринги этого одного метода)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +    def on_new_torrent_process(self, torrent, plugin_obj):
* Давай методы все делаем просто on_new_torrent, on_start, ...
* Вызывается этот когда торрент новый найден? Или когда тело торрент-файла скачано? Или когда что-то другое произошло?

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/base.py
> +        Called in the end of the main process.
Тут опиши, что можно делать. Типа "Does some cleanup after the main workflow has ended."

2017-02-14 10:54 UTC, LuckyGeck commented on shows_updater.py
> +#!./venv/bin/python
Noooooo!!!! Не делай так. А вдруг у меня venv в другом месте лежит? А вдург venv-а нету?

2017-02-14 10:54 UTC, LuckyGeck commented on shows_updater.py
> +    torrent_dicts = json.load(open(path, 'r', 'utf8'), encoding=encoding)
Предлагается убрать encoding из настроек. Тут вот к примеру ты файл уже в utf8 читаешь... Зачем тогда encoding?

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/twitter_notif.py
> +        message_args.update({
Можно в update сделать прием аргументов через kwargs. И тогда вызов будет message_args.update(url=url)

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/telegram_notif.py
> +        msg_args = torrent.dump().copy()
Омг. Тут и dump и copy ) В других местах не так

2017-02-14 10:54 UTC, LuckyGeck commented on plugins/nnm-club.py
> +    def __str__(self):
__str__ = base.Torrent.__str__ или как-то так?

2017-05-26 13:28 UTC, bamx23 commented on plugins/__init__.py
> +        Return server plugin with specific name
Поправил

2017-05-26 13:28 UTC, bamx23 commented on plugins/__init__.py
> +        Return server plugin that can process specific torrent
Поправил

2017-05-26 13:28 UTC, bamx23 commented on plugins/__init__.py
> +        Process all plugins that handle new torrent loads.
Сделал `Triggers 'on_new_torrent' for all registered plugins.`

2017-05-26 13:28 UTC, bamx23 commented on plugins/base.py
> +        import hashlib
Окей, вынес

2017-05-26 13:28 UTC, bamx23 commented on plugins/base.py
> +        :return: True if torrent could be processed with this plugin
Исправил

2017-05-26 13:28 UTC, bamx23 commented on plugins/base.py
> +        :return: Data of torrent file in string representation and
Да, было дело, но отказался. Поправил коммент

2017-05-26 13:28 UTC, bamx23 commented on plugins/nnm-club.py
> +    def __str__(self):
Не понял. В смысле что надо добавлять к базовому формату?

2017-05-26 13:29 UTC, bamx23 commented
Вроде с большего всё поправил.
Однострочные комменты PyCharm не воспринимает как docstring.

2017-07-20 08:00 UTC, merged